name: ZAP Baseline Scan

on:
  schedule:
    - cron: '42 6 * * 1'
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0
        with:
          target: 'https://roguehunter7.github.io/ToDoApp/'
          rules_file_name: '.zap/rules.tsv'
          allow_issue_writing: false
          fail_action: true
